#!/usr/bin/env python3
"""Emit a Fortran OpenMP-offload program with N filler target regions plus one
victim kernel. Usage: gen.py N > repro_N.f90

Every target region contributes about one access to each DeviceRTL state global,
so past ~512 kernels the AAPointerInfo access cap fires and the whole image loses
OpenMPOpt's parallel-region protocol cleanup: +512 B LDS on every kernel and
marshalling spill code in the victim.
"""
import sys

n = int(sys.argv[1])

print("""! Generated by gen.py -- do not edit.
module m
  implicit none
  integer, parameter :: wp = kind(1.0d0)
  real(wp), allocatable :: a(:), b(:), c(:)
contains

  ! Recursive => not inlinable => the kernel keeps the DeviceRTL state live,
  ! which is what makes each kernel contribute accesses to the state globals.
  recursive function dt_work(x, d) result(r)
    !$omp declare target
    real(wp), intent(in) :: x
    integer, intent(in) :: d
    real(wp) :: r
    if (d <= 0) then
      r = x
    else
      r = dt_work(x * 0.5_wp + 1._wp, d - 1)
    end if
  end function dt_work

  ! VICTIM: enough live state to show marshalling spills when the protocol
  ! cleanup fails. Its source never changes; only the filler count does.
  subroutine victim(n)
    integer, intent(in) :: n
    integer :: i
    real(wp) :: t0, t1, t2, t3, t4, t5, t6, t7
    !$omp target teams distribute parallel do private(t0, t1, t2, t3, t4, t5, t6, t7)
    do i = 2, n - 1
      t0 = a(i); t1 = a(i - 1); t2 = a(i + 1)
      t3 = t0 * t1 + t2; t4 = t1 * t2 + t0; t5 = t2 * t0 + t1
      t6 = t3 * t4 + t5; t7 = t4 * t5 + t3
      b(i) = t6 * t7 + t3 * t4 * t5 + dt_work(t0, 2)
      c(i) = (t6 + t7) * (t3 - t4) + (t5 * t0 - t1 * t2)
    end do
  end subroutine victim
""")

for k in range(n):
    print(f"""  subroutine filler{k}(n)
    integer, intent(in) :: n
    integer :: i
    real(wp) :: tmp(n)            ! runtime-sized local: forces globalization
    !$omp target map(to: n) map(tofrom: tmp)
    !$omp teams
    !$omp distribute parallel do
    do i = 1, n
      tmp(i) = dt_work(a(i), mod(i, 3)) + {k}._wp
    end do
    !$omp end distribute parallel do
    !$omp end teams
    !$omp end target
    b(1) = b(1) + tmp(1)
  end subroutine filler{k}
""")

print("""end module m

program p
  use m
  implicit none
  integer, parameter :: n = 1024
  allocate (a(n), b(n), c(n))
  a = 1._wp; b = 0._wp; c = 0._wp
  !$omp target enter data map(to: a) map(alloc: b, c)
  call victim(n)""")

for k in range(n):
    print(f"  call filler{k}(n)")

print("""  !$omp target exit data map(from: b, c)
  write (*, *) 'checksum', sum(b) + sum(c)
end program""")
